[tool.poetry]
name = "mcp-server-independent"
version = "0.1.0"
description = ""
authors = ["PrecIQ IO AI <preciq@preciq.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastmcp = "^2.14.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
